apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bulletin-board
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    remote_write:
      - url: "https://monitoring.api.cloud.yandex.net/prometheus/workspaces/${WORKSPACE_ID}/api/v1/write"
        bearer_token_file: "/etc/prometheus-secrets/api-key"

    scrape_configs:
      - job_name: 'spring-boot-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['bulletin-app.bulletin-board.svc.cluster.local:9090']
            labels:
              application: 'bulletin-board'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-agent
  namespace: bulletin-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-agent
  template:
    metadata:
      labels:
        app: prometheus-agent
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--enable-feature=agent"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: secret-volume
              mountPath: /etc/prometheus-secrets
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: secret-volume
          secret:
            secretName: observability-secret
