app:
  replicaCount: 3
  image:
    repository: ghcr.io/dobro10k2/project-devops-deploy
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

postgres:
  image: postgres:15
  storageSize: 2Gi
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

ingress:
  host: "" # Переопределяется в CI/CD через --set ingress.host
