apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bulletin_board"
  SPRING_DATASOURCE_USERNAME: "postgres"
  JAVA_OPTS: "-Xms256m -Xmx512m"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "bulletin_board"
  STORAGE_S3_BUCKET: "terraform-state-bulletin-dobro10k2"
  STORAGE_S3_ENDPOINT: "https://storage.yandexcloud.net"
  STORAGE_S3_REGION: "ru-central1"
