apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observability-secret-es
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: yandex-lockbox
    kind: SecretStore
  target:
    name: observability-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: "{{ .Values.lockboxSecretId }}"
        property: OBSERVABILITY_API_KEY
