apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  S3_ACCESS_KEY: {{ .Values.secrets.awsAccessKeyId | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  APP_SECRET: {{ .Values.secrets.appSecret | quote }}
