apiVersion: external-secrets.io/v1 # <-- ИСПРАВЛЕНО НА v1
kind: SecretStore
metadata:
  name: yandex-lockbox
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
