name: Deploy to Yandex Cloud K8s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes Access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Create Namespace
        run: kubectl apply -f k8s/namespace.yaml

      - name: Deploy Application with Helm
        run: |
          helm upgrade --install bulletin-board ./k8s/bulletin-board \
            --namespace bulletin-board \
            --set ingress.host="${{ secrets.APP_DOMAIN }}" \
            --set secrets.dbPassword="${{ secrets.DB_PASSWORD }}" \
            --set secrets.awsAccessKeyId="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --set secrets.awsSecretAccessKey="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --set secrets.appSecret="${{ secrets.APP_SECRET }}" \
            --wait

      - name: Deploy Observability (Prometheus & Fluent Bit)
        env:
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          OBSERVABILITY_API_KEY: ${{ secrets.OBSERVABILITY_API_KEY }}
          LOG_GROUP_ID: ${{ secrets.LOG_GROUP_ID }}
        run: |
          make k8s-deploy-monitoring
          make k8s-install-logging
